name: Test and Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          check-latest: true
          cache: gradle

      - name: Change Script Ownership
        run: chmod +x ./gradlew

      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      - name: Run Android Linter
        run: ./gradlew lint